//! Microbench for the Q4_K × Q8_K row-dot kernel and surrounding loop.
//!
//! Goal: explain the gap between the observed CPU-FFN per-token time
//! (~177 ms for the FFN stages on Qwen3.6-35B-A3B) and the theoretical
//! peak (~1 ms with 24 cores × AVX2). The bench separates four layers
//! of overhead:
//!
//! 1. `kernel_only`    — peak inner-loop time (single row, no rayon).
//! 2. `matvec_serial`  — 1 thread × 1408 rows (per-thread work for one matvec).
//! 3. `matvec_parallel`— rayon par_iter × 1408 rows (real matvec call).
//! 4. `moe_step`       — 24 sequential matvecs (= one MoE FFN block).
//!
//! Numbers `1` → `4` should grow proportionally; gaps reveal where the
//! cost actually lives (rayon spawn, function-call overhead, etc.).
//!
//! Run with:
//!   cargo bench -p larql-models --bench q4k_q8k_kernel
//!
//! Synthetic Q4_K / Q8_K data is generated by quantising random f32
//! input so the row dot exercises a realistic numerical range — not
//! all-zeros which the kernel might short-circuit on some paths.

use criterion::{black_box, criterion_group, criterion_main, Criterion, Throughput};
use larql_models::quant::ggml::q4_k::dequantize_q4_k;
use larql_models::quant::ggml::q4k_q8k::q4k_q8k_row_dot;
use larql_models::quant::ggml::q4k_q8k::quantize_to_q8_k;
use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha20Rng;
use rayon::prelude::*;

const Q4K_BLOCK_BYTES: usize = 144;

/// Qwen3.6-35B-A3B hidden size — used as the per-row Q4_K block width.
const HIDDEN: usize = 2048;

/// Qwen3.6-35B-A3B MoE intermediate (per-expert ffn_dim). Rows in
/// `gate` and `up`; columns in `down`.
const FFN_DIM: usize = 1408;

/// `top_k = 8` experts, each with 3 matvecs (gate, up, down).
const MOE_MATVECS_PER_STEP: usize = 8 * 3;

/// Build one row of valid-shape Q4_K bytes from random bytes. We
/// don't have a public Q4_K encoder in-crate, but for *throughput*
/// the kernel only needs valid layout (144 bytes/super-block × N
/// super-blocks); the numerical result is irrelevant. We set the
/// scale/min f16 fields to small non-zero values so the f16→f32
/// conversion produces normal numbers (avoids any subnormal stalls
/// the CPU might insert for denormals).
fn synth_q4k_bytes(n_super_blocks: usize, seed: u64) -> Vec<u8> {
    let mut rng = ChaCha20Rng::seed_from_u64(seed);
    let mut bytes = vec![0u8; n_super_blocks * Q4K_BLOCK_BYTES];
    for sb in 0..n_super_blocks {
        let off = sb * Q4K_BLOCK_BYTES;
        // f16 super-block scale ≈ 0.0625 (0x2C00 in IEEE 754 binary16
        // is ≈ 0.0625, the actual encoding for 1.0 / 16). Doesn't have
        // to be exact — just non-zero / non-denormal.
        bytes[off] = 0x00;
        bytes[off + 1] = 0x2C;
        // f16 super-block min ≈ 0.0
        bytes[off + 2] = 0x00;
        bytes[off + 3] = 0x00;
        // 12 bytes of sub-block scales/mins — random but bounded.
        for i in 0..12 {
            bytes[off + 4 + i] = rng.r#gen::<u8>() & 0x3F; // 6-bit safe
        }
        // 128 bytes of packed 4-bit quants — fully random.
        for i in 0..128 {
            bytes[off + 16 + i] = rng.r#gen::<u8>();
        }
    }
    bytes
}

/// Build one row (HIDDEN / 256 super-blocks).
fn synth_q4k_row(seed: u64) -> Vec<u8> {
    synth_q4k_bytes(HIDDEN / 256, seed)
}

/// Build a full `[FFN_DIM, HIDDEN]` matrix of Q4_K rows.
fn synth_q4k_matrix(seed: u64) -> Vec<u8> {
    let row_blocks = HIDDEN / 256;
    let total_blocks = FFN_DIM * row_blocks;
    synth_q4k_bytes(total_blocks, seed)
}

/// Build the Q8_K activation buffer (`x` post-Q8_K-quantise).
fn synth_q8k_x(seed: u64) -> Vec<u8> {
    let mut rng = ChaCha20Rng::seed_from_u64(seed);
    let x: Vec<f32> = (0..HIDDEN).map(|_| rng.gen_range(-1.0_f32..1.0)).collect();
    quantize_to_q8_k(&x)
}

fn bench_q4k_q8k(c: &mut Criterion) {
    let q4k_row = synth_q4k_row(0xC0FFEE);
    let q4k_matrix = synth_q4k_matrix(0xDEADBEEF);
    let q8k_x = synth_q8k_x(0x1234_5678);
    let row_bytes = q4k_row.len();

    // Sanity: a single row dot should produce a finite scalar.
    let probe = q4k_q8k_row_dot(&q4k_row, &q8k_x).expect("kernel sanity");
    assert!(
        probe.is_finite(),
        "kernel produced non-finite output: {probe}"
    );

    // ── 1. Inner kernel only — single row dot, no rayon. ─────────────
    {
        let mut g = c.benchmark_group("q4k_q8k/kernel_only");
        g.throughput(Throughput::Elements(HIDDEN as u64));
        g.bench_function("row_dot_2048", |b| {
            b.iter(|| {
                let r = q4k_q8k_row_dot(black_box(&q4k_row), black_box(&q8k_x)).expect("kernel");
                black_box(r);
            })
        });
        g.finish();
    }

    // ── 2. Single-thread matvec: 1408 sequential row dots. ───────────
    //    Tells us how long a per-thread chunk would take if rayon
    //    split work perfectly across 1 thread.
    {
        let mut g = c.benchmark_group("q4k_q8k/matvec_serial");
        g.throughput(Throughput::Elements((FFN_DIM * HIDDEN) as u64));
        g.bench_function("matvec_1408x2048", |b| {
            b.iter(|| {
                let mut out = vec![0.0_f32; FFN_DIM];
                for r in 0..FFN_DIM {
                    let row = &q4k_matrix[r * row_bytes..(r + 1) * row_bytes];
                    out[r] = q4k_q8k_row_dot(black_box(row), black_box(&q8k_x)).expect("kernel");
                }
                black_box(out);
            })
        });
        g.finish();
    }

    // ── 3. Rayon par_iter matvec — what `QuantTensor::matvec` does. ──
    {
        let mut g = c.benchmark_group("q4k_q8k/matvec_parallel");
        g.throughput(Throughput::Elements((FFN_DIM * HIDDEN) as u64));
        g.bench_function("matvec_1408x2048_par", |b| {
            b.iter(|| {
                let mut out = vec![0.0_f32; FFN_DIM];
                out.par_iter_mut().enumerate().for_each(|(r, out_r)| {
                    let row = &q4k_matrix[r * row_bytes..(r + 1) * row_bytes];
                    *out_r = q4k_q8k_row_dot(black_box(row), black_box(&q8k_x)).expect("kernel");
                });
                black_box(out);
            })
        });
        g.finish();
    }

    // ── 4. Full MoE-step shape — 24 sequential matvec calls. ─────────
    //    Mirrors `swiglu_moe_lazy`: 8 experts × (gate + up + down)
    //    sequential, each parallel internally. Compares directly to
    //    the FINE_PROFILE FFN_GATE_UP_PAIR + FFN_DOWN total (~177 ms
    //    on this host).
    {
        let mut g = c.benchmark_group("q4k_q8k/moe_step");
        g.throughput(Throughput::Elements(
            (MOE_MATVECS_PER_STEP * FFN_DIM * HIDDEN) as u64,
        ));
        // Sample size kept small — each iteration runs 24 par_iter
        // matvecs, so the bench takes a while.
        g.sample_size(10);
        g.bench_function("moe_24x_matvec", |b| {
            b.iter(|| {
                for _ in 0..MOE_MATVECS_PER_STEP {
                    let mut out = vec![0.0_f32; FFN_DIM];
                    out.par_iter_mut().enumerate().for_each(|(r, out_r)| {
                        let row = &q4k_matrix[r * row_bytes..(r + 1) * row_bytes];
                        *out_r =
                            q4k_q8k_row_dot(black_box(row), black_box(&q8k_x)).expect("kernel");
                    });
                    black_box(out);
                }
            })
        });
        g.finish();
    }

    // ── 5. Inverted parallelism: par over experts, serial inside. ────
    //    Hypothesis from runs 1-4: each individual matvec is too small
    //    for 48-thread rayon (only 1408 rows / 48 = 30 rows per thread).
    //    Spawn overhead dominates per-call. If we instead parallelise
    //    *across* the 8 experts (each thread runs its own 3 sequential
    //    matvecs), per-thread work jumps from ~115μs to ~492μs and
    //    rayon overhead becomes a small fraction.
    {
        let mut g = c.benchmark_group("q4k_q8k/moe_step_par_outer");
        g.throughput(Throughput::Elements(
            (MOE_MATVECS_PER_STEP * FFN_DIM * HIDDEN) as u64,
        ));
        g.sample_size(10);
        g.bench_function("moe_8experts_par_3serial_inside", |b| {
            b.iter(|| {
                // Pretend we have 8 distinct experts; we reuse the same
                // matrix bytes since the bench is about scheduling, not
                // memory. Each expert thread does 3 serial matvecs.
                let outputs: Vec<Vec<f32>> = (0..8)
                    .into_par_iter()
                    .map(|_expert| {
                        let mut out_chain = vec![0.0_f32; FFN_DIM];
                        for _matvec in 0..3 {
                            for r in 0..FFN_DIM {
                                let row = &q4k_matrix[r * row_bytes..(r + 1) * row_bytes];
                                out_chain[r] = q4k_q8k_row_dot(black_box(row), black_box(&q8k_x))
                                    .expect("kernel");
                            }
                        }
                        out_chain
                    })
                    .collect();
                black_box(outputs);
            })
        });
        g.finish();
    }

    // ── 6. Q4_K dequantise (for comparison — host f32 path). ─────────
    //    Reveals how much time `dequantize_q4_k` alone takes — useful
    //    to gauge whether the Q4_K → f32 → dot path could beat the
    //    Q4_K × Q8_K kernel.
    {
        let mut g = c.benchmark_group("q4k_q8k/dequant_only");
        g.throughput(Throughput::Elements(HIDDEN as u64));
        g.bench_function("dequant_row_2048", |b| {
            b.iter(|| {
                let f = dequantize_q4_k(black_box(&q4k_row), HIDDEN).expect("dequant");
                black_box(f);
            })
        });
        g.finish();
    }
}

criterion_group!(benches, bench_q4k_q8k);
criterion_main!(benches);
