#!/usr/bin/env python3
"""Regenerate the hermetic Gated DeltaNet fixture.

Writes `crates/larql-vindex/src/format/vindex3/opplan/exec/tests/
qw2_tiny_fixture.rs`. Requires `transformers` and `torch`; it is NOT part of
any build, only run when the operator's reference semantics change.

The reference is HF's own operator composition at reduced geometry --
`F.linear`, `F.conv1d` and `torch_recurrent_gated_delta_rule`. Nothing here
reimplements the recurrence: a fixture generated by our own arithmetic would
only prove the Rust agrees with the Python.

Weights are NOT stored. They come from `lcg_values` on both sides, which is
replicated below bit-for-bit -- so only the expected outputs are committed,
and `LCG_PROBE` catches the generator drifting apart from this copy.
"""
import os
import sys

import numpy as np
import torch
import torch.nn.functional as F
from transformers.models.qwen3_5.modeling_qwen3_5 import torch_recurrent_gated_delta_rule

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "crates/larql-vindex/src/format/vindex3/opplan/exec/tests/qw2_tiny_fixture.rs",
)

MASK = (1 << 64) - 1
MUL = 6364136223846793005
INC = 1442695040888963407


def lcg(n, seed):
    """`crates/larql-vindex/src/format/vindex3/fixtures.rs::lcg_values`."""
    st = ((seed * MUL) + INC) & MASK
    out = []
    for _ in range(n):
        st = ((st * MUL) + INC) & MASK
        unit = (st >> 33) / float(1 << 31)
        out.append(np.float32(np.float64(unit - 0.5) * np.float64(0.1)))
    return np.array(out, dtype=np.float32)


# Small enough to embed; large enough that every stage runs and the head
# expansion is a real 3x, the ratio Qwen3.8 itself uses.
HID, HK, HV, DK, DV, KER, T = 32, 2, 6, 8, 8, 4, 3
KEY, VAL = HK * DK, HV * DV
CONV = KEY * 2 + VAL
EPS = 1e-6


def main() -> int:
    def t(a, shape):
        return torch.from_numpy(a.reshape(shape).copy())

    Wq = t(lcg(CONV * HID, 1), (CONV, HID))
    Wa = t(lcg(HV * HID, 2), (HV, HID))
    Wb = t(lcg(HV * HID, 3), (HV, HID))
    Wz = t(lcg(VAL * HID, 4), (VAL, HID))
    Wc = t(lcg(CONV * KER, 5), (CONV, 1, KER))
    Al = t(lcg(HV, 6), (HV,))
    dt = t(lcg(HV, 7), (HV,))
    Wn = t(lcg(DV, 8), (DV,))
    Wo = t(lcg(HID * VAL, 9), (HID, VAL))
    h = t(lcg(T * HID, 10), (1, T, HID))

    mixed = F.linear(h, Wq)
    conv = F.silu(
        F.conv1d(mixed.transpose(1, 2), Wc, groups=CONV, padding=KER - 1)[:, :, :T]
    ).transpose(1, 2)
    q, k, v = torch.split(conv, [KEY, KEY, VAL], dim=-1)
    q = q.reshape(1, T, -1, DK)
    k = k.reshape(1, T, -1, DK)
    v = v.reshape(1, T, -1, DV)
    z = F.linear(h, Wz)
    beta = F.linear(h, Wb).sigmoid()
    g = -Al.float().exp() * F.softplus(F.linear(h, Wa).float() + dt)
    rep = HV // HK
    q = q.repeat_interleave(rep, dim=2)
    k = k.repeat_interleave(rep, dim=2)

    state, cores, outs = None, [], []
    for i in range(T):
        core, state = torch_recurrent_gated_delta_rule(
            q[:, i : i + 1], k[:, i : i + 1], v[:, i : i + 1],
            g=g[:, i : i + 1], beta=beta[:, i : i + 1],
            initial_state=state, output_final_state=True,
            use_qk_l2norm_in_kernel=True,
        )
        x = core.reshape(-1, DV).float()
        var = x.pow(2).mean(-1, keepdim=True)
        x = Wn * (x * torch.rsqrt(var + EPS)) * F.silu(z[:, i : i + 1].reshape(-1, DV).float())
        outs.append(F.linear(x.reshape(1, 1, -1), Wo))
        cores.append(core)

    def fmt(a, per=6):
        vals = np.asarray(a, dtype=np.float32).ravel()
        return "\n".join(
            "    " + " ".join(f"{x:.9e}," for x in vals[i : i + per])
            for i in range(0, len(vals), per)
        )

    src = f'''//! Generated by `scripts/gen_gated_delta_fixture.py`. Do not hand-edit.
//!
//! A deliberately small Gated DeltaNet, produced through HF's OWN operator
//! composition at reduced geometry. Hermetic: weights come from
//! `lcg_values` on both sides, so only the expected outputs live here.

// Every literal is an exact f32 printed at full precision. Rounding them to
// what clippy considers sufficient would silently move the expectations
// this file exists to pin.
#![allow(clippy::excessive_precision)]

/// hidden {HID}, key heads {HK}, value heads {HV}, head dims {DK}/{DV},
/// conv kernel {KER}, {T} positions. `{HV}/{HK}` is a real 3x expansion,
/// the same ratio Qwen3.8 uses.
pub const HIDDEN: usize = {HID};
pub const KEY_HEADS: usize = {HK};
pub const VALUE_HEADS: usize = {HV};
pub const KEY_HEAD_DIM: usize = {DK};
pub const VALUE_HEAD_DIM: usize = {DV};
pub const CONV_KERNEL: usize = {KER};
pub const POSITIONS: usize = {T};
pub const NORM_EPS: f32 = {EPS:e};

/// Seeds for `lcg_values`, in the order the generator used them.
pub const SEED_IN_PROJ_QKV: u64 = 1;
pub const SEED_IN_PROJ_A: u64 = 2;
pub const SEED_IN_PROJ_B: u64 = 3;
pub const SEED_IN_PROJ_Z: u64 = 4;
pub const SEED_CONV1D: u64 = 5;
pub const SEED_A_LOG: u64 = 6;
pub const SEED_DT_BIAS: u64 = 7;
pub const SEED_NORM: u64 = 8;
pub const SEED_OUT_PROJ: u64 = 9;
pub const SEED_INPUT: u64 = 10;

/// The first four values seed 1 produced when this fixture was generated.
/// If `lcg_values` ever changes, every expectation below silently describes
/// different weights — so the drift is caught here instead of surfacing as
/// an inexplicable parity failure.
pub const LCG_PROBE: [f32; 4] = [
{fmt(lcg(4, 1))}
];

/// `[POSITIONS][VALUE_HEADS * KEY_HEAD_DIM]`, post-conv and post-expansion.
/// The sentinel for convolution ordering and head-expansion defects.
pub const EXPECTED_Q: [f32; {T * HV * DK}] = [
{fmt(q)}
];

/// `[POSITIONS][VALUE_HEADS * VALUE_HEAD_DIM]` — the recurrence sentinel.
pub const EXPECTED_CORE: [f32; {T * VAL}] = [
{fmt(torch.cat(cores, dim=1))}
];

/// State after the final position — the write-path sentinel. A wrong
/// intermediate state reaches here through the chain.
pub const EXPECTED_FINAL_STATE: [f32; {HV * DK * DV}] = [
{fmt(state)}
];

/// `[POSITIONS][HIDDEN]` — the end-to-end sentinel (gated norm + out_proj).
pub const EXPECTED_OUTPUT: [f32; {T * HID}] = [
{fmt(torch.cat(outs, dim=1))}
];
'''
    with open(OUT, "w") as fh:
        fh.write(src)
    print(f"wrote {OUT} ({len(src) / 1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
